export const CAR_LIST_REQUEST = 'CAR_LIST_REQUEST'
export const CAR_LIST_SUCCESS = 'CAR_LIST_SUCCESS'
export const CAR_LIST_FAIL = 'CAR_LIST_FAIL'

export const CAR_DETAIL_REQUEST = 'CAR_DETAIL_REQUEST'
export const CAR_DETAIL_SUCCESS = 'CAR_DETAIL_SUCCESS'
export const CAR_DETAIL_FAIL = 'CAR_DETAIL_FAIL'
